### ISSUE TITLE
menuext text is not showing

### ISSUE THREAD

**Issue by hcgreier** [cosmocode/dokuwiki-plugin-menuext#1]
Hi!
Great plugin!
I put the menuext.json file into folder [DOKUWIKI_PATH]/conf/menuext.json
In the page edit flyout, the icon shows up, but there is no text beside it, just blank.

Wiki is here: http://www.hcgreier.at/andreawiki/doku.php?id=start

The URL works, opens the equation editor installed locally on same server.

Here is my json:

`{
  "page": [
    {
      "order": 5,
      "label": {
        "de": "Formeleditor"
      },
      "title": {
        "de": "Formeleditor"
      },
      "link": "http://www.hcgreier.at/andreawiki/vme/VisualMathEditor.html",
      "svg": "math-integral.svg",
      "attr": {
        "target": "_blank"
      }
    }
  ]
}`

Thanks!
hc

**Comment by splitbrain** [comment]
I can't reproduce this. Works fine for me (with language set to 'de').

**Comment by splitbrain** [comment]
Ah, your language is de-informal but you only defined de labels.

**Comment by hcgreier** [comment]
Ah, that simple. I'm sorry for the inconvenience ;)
Works now.
Thank you very much!
